name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [20.x]
    steps:
    - name: Install dependencies
      run: cd apps/api && npm install
    - name: Deploy to AWS
      run: cd apps/api && npm run deploy:prod

